### ISSUE TITLE
DELETE Homework

### ISSUE THREAD

**Issue by mkmoisen** [cheshireoctopus/course_mgmt#49]
As a Admin or Teacher, I want to be able to delete Homeworks, to delete the association between a Homework and a Course, and to delete the association between a Homework and a Class.

**Comment by mkmoisen** [comment]
How should the logic be handled for the following case:

We are halfway through a given Class iteration of some Course. The admin decides that he wants to delete the association between some Homework and the Course in question. Should this have any effect on the current Class iteration? I'm assuming it should not and will program it as such. Let me know what you think.

**Comment by cheshireoctopus** [comment]
@mkmoisen Do not understand the relationship between a the `homework` and `course` models - believed that only `class` and `homework` models were associated?

Assuming a relationship between `homework` and `course` models, no, deleting `homework` should not have an impact on current/existing class iterations.

**Comment by mkmoisen** [comment]
`Homework` is associated to both `Course` and to `Class` via the `CourseHomework` and `ClassHomework` tables, respectively.

The purpose of this is to allow an Admin to create "template" Homeworks for a Course, such that when a Class is created from a Course, all of the Homeworks for the Class (`ClassHomework`) will be automatically instantiated from the templates in `CourseHomework`. 

If a Teacher wants to modify a particular `Homework` for a particular `Class`, perhaps because the students in this Class are very smart and the teacher wants to add more work, the teacher can do so without affecting the homework "templates" associated at the Course level.

This same system is also true for Lecture.

Make sure to read the documentation for Homework PUT and Lecture PUT which I think explains it well, and let me know if I can clarify anything.

**Comment by cheshireoctopus** [comment]
> The purpose of this is to allow an Admin to create "template" Homeworks for a Course, such that when a Class is created from a Course, all of the Homeworks for the Class (ClassHomework) will be automatically instantiated from the templates in CourseHomework.

Got it. To confirm, deleting `homeworks` and `lectures` at the course level should not remove them from `class` instance?
